#!/usr/bin/env python3
"""Compare the human pilot against existing aggregate CivBench model runs.

This is not a matched-question human/model comparison. The human pilot worlds
are absent from the existing model-evaluation run. Instead, this script extracts
the closest aggregate proxy: continuous city/tech/treasury questions at the
same H1/H3/H4/H6 resolution turns from the main non-H0 model run.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
import re
from collections import defaultdict
from pathlib import Path
from statistics import mean


QUANTILE_LEVELS = {"p10": 0.10, "p25": 0.25, "p50": 0.50, "p75": 0.75, "p90": 0.90}

TURN_TO_HORIZON = {
    90: "H1",
    120: "H2",
    150: "H3",
    180: "H4",
    210: "H5",
    240: "H6",
    270: "H7",
}

HUMAN_TEMPLATE_TO_MODEL_TEMPLATE = {
    "cities": "cities_count_continuous",
    "techs": "techs_continuous",
    "treasury": "treasury_continuous",
}

MODEL_TEMPLATE_TO_HUMAN_TEMPLATE = {v: k for k, v in HUMAN_TEMPLATE_TO_MODEL_TEMPLATE.items()}

HUMAN_HORIZONS = {"H1", "H3", "H4", "H6"}

COMPARISON_SETTINGS = {
    "primary_same_targets_same_horizons": {
        "description": (
            "Closest aggregate proxy: same continuous target families as the human pilot "
            "(cities, technologies, gold/treasury) and the same H1/H3/H4/H6 resolution turns. "
            "Worlds and civilizations differ."
        ),
        "templates": set(MODEL_TEMPLATE_TO_HUMAN_TEMPLATE),
        "horizons": HUMAN_HORIZONS,
        "normalized": True,
        "comparison_grade": "closest_aggregate_proxy",
    },
    "same_targets_all_nonh0_horizons": {
        "description": (
            "Same continuous target families as the human pilot, but all non-H0 model-run "
            "horizons H1-H7. Useful as a horizon-selection robustness check."
        ),
        "templates": set(MODEL_TEMPLATE_TO_HUMAN_TEMPLATE),
        "horizons": set(TURN_TO_HORIZON.values()),
        "normalized": True,
        "comparison_grade": "target_matched_broader_horizons",
    },
    "all_continuous_all_nonh0": {
        "description": (
            "All continuous questions in the model run. This includes population, score, "
            "and territory targets not shown to humans, so it is context only."
        ),
        "templates": None,
        "horizons": set(TURN_TO_HORIZON.values()),
        "normalized": False,
        "comparison_grade": "context_only_not_human_equivalent",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model-run",
        type=Path,
        default=Path("data/evaluations/runs/final_2026-03-07_newq_uncond_nonh0_bin_plus_cont_all30.json"),
        help="Existing model-evaluation JSON containing continuous model forecasts.",
    )
    parser.add_argument(
        "--human-analysis-dir",
        type=Path,
        default=Path("data/human_baseline/analysis"),
        help="Directory generated by scripts/analyze_human_baseline.py.",
    )
    parser.add_argument(
        "--human-questions",
        type=Path,
        default=Path("data/human_baseline/questions.csv"),
        help="Human pilot question manifest, used for target ranges and coverage.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/human_baseline/aggregate_model_comparison"),
        help="Directory for comparison outputs.",
    )
    parser.add_argument("--bootstrap-samples", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=20260429)
    return parser.parse_args()


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict], fieldnames: list[str] | None = None) -> None:
    if fieldnames is None:
        keys = []
        seen = set()
        for row in rows:
            for key in row:
                if key not in seen:
                    keys.append(key)
                    seen.add(key)
        fieldnames = keys
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def quantile_crps(percentiles: dict[str, float], true_value: float) -> float:
    total_loss = 0.0
    for key, tau in QUANTILE_LEVELS.items():
        residual = true_value - percentiles[key]
        if residual >= 0:
            total_loss += tau * residual
        else:
            total_loss += (tau - 1) * residual
    return (2 / len(QUANTILE_LEVELS)) * total_loss


def percentile(values: list[float], pct: float) -> float:
    ordered = sorted(values)
    if not ordered:
        return float("nan")
    idx = (len(ordered) - 1) * pct
    lo = math.floor(idx)
    hi = math.ceil(idx)
    if lo == hi:
        return ordered[lo]
    frac = idx - lo
    return ordered[lo] * (1 - frac) + ordered[hi] * frac


def bootstrap_ci(values: list[float], samples: int, rng: random.Random) -> tuple[float, float]:
    if not values:
        return float("nan"), float("nan")
    n = len(values)
    draws = []
    for _ in range(samples):
        draws.append(sum(rng.choices(values, k=n)) / n)
    return percentile(draws, 0.025), percentile(draws, 0.975)


def bootstrap_diff_ci(
    model_values: list[float],
    human_values: list[float],
    samples: int,
    rng: random.Random,
) -> tuple[float, float]:
    """Bootstrap model mean minus human mean under independent samples."""
    if not model_values or not human_values:
        return float("nan"), float("nan")
    model_n = len(model_values)
    human_n = len(human_values)
    draws = []
    for _ in range(samples):
        model_mean = sum(rng.choices(model_values, k=model_n)) / model_n
        human_mean = sum(rng.choices(human_values, k=human_n)) / human_n
        draws.append(model_mean - human_mean)
    return percentile(draws, 0.025), percentile(draws, 0.975)


def infer_horizon(question_text: str) -> tuple[int | None, str | None]:
    match = re.search(r"turn\s+(\d+)", question_text)
    if not match:
        return None, None
    turn = int(match.group(1))
    return turn, TURN_TO_HORIZON.get(turn)


def valid_percentiles(prediction: dict) -> dict[str, float] | None:
    percentiles = prediction.get("percentiles")
    if not isinstance(percentiles, dict):
        return None
    try:
        return {key: float(percentiles[key]) for key in QUANTILE_LEVELS}
    except (KeyError, TypeError, ValueError):
        return None


def load_human_ranges(path: Path) -> dict[str, float]:
    ranges = {}
    for row in read_csv(path):
        template = row["template"]
        value_range = float(row["bin_max"]) - float(row["bin_min"])
        if template in ranges and not math.isclose(ranges[template], value_range):
            raise ValueError(f"Inconsistent human range for {template}")
        ranges[template] = value_range
    return ranges


def score_model_questions(model_run: dict, human_ranges: dict[str, float]) -> tuple[list[dict], dict]:
    score_rows = []
    coverage = {
        "continuous_questions": 0,
        "continuous_by_template": defaultdict(int),
        "continuous_by_horizon": defaultdict(int),
        "model_failures_by_model": defaultdict(int),
    }

    models = list(model_run["model_results"].keys())
    for question in model_run["questions"]:
        if question.get("question_type") != "continuous":
            continue
        turn, horizon = infer_horizon(question["question_text"])
        template_id = question["template_id"]
        human_template = MODEL_TEMPLATE_TO_HUMAN_TEMPLATE.get(template_id)
        value_range = human_ranges.get(human_template) if human_template else None
        coverage["continuous_questions"] += 1
        coverage["continuous_by_template"][template_id] += 1
        coverage["continuous_by_horizon"][horizon or "unknown"] += 1

        for model_id in models:
            prediction = question["predictions"].get(model_id, {})
            percentiles = valid_percentiles(prediction)
            if percentiles is None:
                coverage["model_failures_by_model"][model_id] += 1
                continue
            crps = quantile_crps(percentiles, float(question["ground_truth"]))
            mae = abs(percentiles["p50"] - float(question["ground_truth"]))
            score_rows.append(
                {
                    "model": model_id,
                    "question_id": question["question_id"],
                    "game_id": question["game_id"],
                    "template_id": template_id,
                    "human_template": human_template or "",
                    "turn": turn or "",
                    "horizon": horizon or "",
                    "ground_truth": float(question["ground_truth"]),
                    "crps": crps,
                    "mae": mae,
                    "normalized_crps": crps / value_range if value_range else "",
                    "normalized_mae": mae / value_range if value_range else "",
                    "p10": percentiles["p10"],
                    "p25": percentiles["p25"],
                    "p50": percentiles["p50"],
                    "p75": percentiles["p75"],
                    "p90": percentiles["p90"],
                }
            )

    coverage["continuous_by_template"] = dict(coverage["continuous_by_template"])
    coverage["continuous_by_horizon"] = dict(coverage["continuous_by_horizon"])
    coverage["model_failures_by_model"] = dict(coverage["model_failures_by_model"])
    return score_rows, coverage


def in_setting(row: dict, setting: dict) -> bool:
    if row["horizon"] not in setting["horizons"]:
        return False
    templates = setting["templates"]
    if templates is not None and row["template_id"] not in templates:
        return False
    return True


def question_key(row: dict) -> tuple:
    return (row["game_id"], row["question_id"], row["template_id"], row["horizon"])


def summarize_model_settings(score_rows: list[dict], models: list[str], samples: int, rng: random.Random) -> tuple[list[dict], dict]:
    rows_by_model = defaultdict(list)
    for row in score_rows:
        rows_by_model[row["model"]].append(row)

    setting_values: dict[tuple[str, str], dict[str, list[float]]] = {}
    summary_rows = []
    for setting_name, setting in COMPARISON_SETTINGS.items():
        for model_id in models:
            total_questions = len(
                {
                    question_key(row)
                    for row in score_rows
                    if in_setting(row, setting)
                }
            )
            model_rows = [row for row in rows_by_model[model_id] if in_setting(row, setting)]
            crps_values = [float(row["crps"]) for row in model_rows]
            mae_values = [float(row["mae"]) for row in model_rows]
            if setting["normalized"]:
                norm_crps_values = [
                    float(row["normalized_crps"])
                    for row in model_rows
                    if row.get("normalized_crps") != ""
                ]
                norm_mae_values = [
                    float(row["normalized_mae"])
                    for row in model_rows
                    if row.get("normalized_mae") != ""
                ]
            else:
                norm_crps_values = []
                norm_mae_values = []
            setting_values[(setting_name, model_id)] = {
                "normalized_crps": norm_crps_values,
                "crps": crps_values,
            }

            norm_lo, norm_hi = bootstrap_ci(norm_crps_values, samples, rng) if norm_crps_values else ("", "")
            summary_rows.append(
                {
                    "setting": setting_name,
                    "comparison_grade": setting["comparison_grade"],
                    "setting_description": setting["description"],
                    "model": model_id,
                    "n_questions_in_setting": total_questions,
                    "n_valid_predictions": len(model_rows),
                    "n_failures_or_missing": total_questions - len(model_rows),
                    "crps": mean(crps_values) if crps_values else "",
                    "crps_ci_low": "",
                    "crps_ci_high": "",
                    "mae": mean(mae_values) if mae_values else "",
                    "normalized_crps": mean(norm_crps_values) if norm_crps_values else "",
                    "normalized_crps_ci_low": norm_lo,
                    "normalized_crps_ci_high": norm_hi,
                    "normalized_mae": mean(norm_mae_values) if norm_mae_values else "",
                }
            )
    return summary_rows, setting_values


def summarize_template_horizon(score_rows: list[dict], models: list[str]) -> list[dict]:
    groups = defaultdict(list)
    primary = COMPARISON_SETTINGS["primary_same_targets_same_horizons"]
    for row in score_rows:
        if in_setting(row, primary):
            groups[(row["model"], row["human_template"], row["horizon"])].append(row)

    out = []
    for (model_id, template, horizon), rows in sorted(groups.items()):
        norm_values = [float(row["normalized_crps"]) for row in rows if row["normalized_crps"] != ""]
        out.append(
            {
                "setting": "primary_same_targets_same_horizons",
                "model": model_id,
                "template": template,
                "horizon": horizon,
                "n_valid_predictions": len(rows),
                "normalized_crps": mean(norm_values) if norm_values else "",
                "crps": mean(float(row["crps"]) for row in rows),
                "mae": mean(float(row["mae"]) for row in rows),
            }
        )
    return out


def load_human_reference(analysis_dir: Path) -> tuple[list[dict], dict[str, list[float]]]:
    aggregate_rows = read_csv(analysis_dir / "aggregate_summary.csv")
    question_rows = read_csv(analysis_dir / "question_summary.csv")
    forecast_rows = read_csv(analysis_dir / "forecast_scores.csv")

    overall = [row for row in aggregate_rows if row["group"] == "overall" and row["value"] == "all"]
    reference_rows = []
    for row in overall:
        reference_rows.append(
            {
                "source": row["source"],
                "n_forecasts": row["n_forecasts"],
                "n_participants": row["n_participants"],
                "n_questions": row["n_questions"],
                "crps": row["crps"],
                "mae": row["mae"],
                "normalized_crps": row["normalized_crps"],
                "normalized_mae": row["normalized_mae"],
                "rps": row["rps"],
            }
        )

    participant_groups = defaultdict(list)
    for row in forecast_rows:
        participant_groups[row["participant_id"]].append(float(row["normalized_crps"]))
    human_values = {
        "human_individual": [mean(values) for values in participant_groups.values()],
        "human_crowd_mean": [float(row["crowd_normalized_crps"]) for row in question_rows],
        "uniform_bins": [float(row["uniform_normalized_crps"]) for row in question_rows],
    }
    return reference_rows, human_values


def compare_to_humans(
    model_summary_rows: list[dict],
    setting_values: dict[tuple[str, str], dict[str, list[float]]],
    human_reference_rows: list[dict],
    human_values: dict[str, list[float]],
    samples: int,
    rng: random.Random,
) -> list[dict]:
    human_points = {row["source"]: float(row["normalized_crps"]) for row in human_reference_rows}
    human_meta = {row["source"]: row for row in human_reference_rows}
    out = []
    primary_settings = [
        "primary_same_targets_same_horizons",
        "same_targets_all_nonh0_horizons",
    ]
    for row in model_summary_rows:
        if row["setting"] not in primary_settings or row["normalized_crps"] == "":
            continue
        model_values = setting_values[(row["setting"], row["model"])]["normalized_crps"]
        for human_source in ["human_crowd_mean", "human_individual", "uniform_bins"]:
            ci_low, ci_high = bootstrap_diff_ci(model_values, human_values[human_source], samples, rng)
            diff = float(row["normalized_crps"]) - human_points[human_source]
            if ci_high < 0:
                descriptive_result = "model_lower_error_ci_excludes_zero"
            elif ci_low > 0:
                descriptive_result = "human_or_uniform_lower_error_ci_excludes_zero"
            else:
                descriptive_result = "descriptive_ci_overlaps_zero"
            out.append(
                {
                    "setting": row["setting"],
                    "model": row["model"],
                    "human_reference": human_source,
                    "model_normalized_crps": row["normalized_crps"],
                    "human_normalized_crps": human_points[human_source],
                    "model_minus_human_normalized_crps": diff,
                    "diff_ci_low": ci_low,
                    "diff_ci_high": ci_high,
                    "descriptive_result": descriptive_result,
                    "n_model_predictions": row["n_valid_predictions"],
                    "n_human_forecasts": human_meta[human_source]["n_forecasts"],
                    "n_human_questions": human_meta[human_source]["n_questions"],
                    "inference_note": (
                        "Independent bootstrap over different question sets; useful for descriptive "
                        "uncertainty, not a confirmatory matched-pair significance test."
                    ),
                }
            )
    return out


def write_readme(path: Path) -> None:
    path.write_text(
        """# Aggregate Human-vs-Model Comparison

Generated by `scripts/compare_human_to_existing_models.py`.

This analysis compares the human pilot to existing model evaluations without rerunning models on the exact human-pilot worlds. The primary comparison is therefore an aggregate proxy, not a matched-question benchmark.

## Files

- `human_reference_summary.csv`: human pilot scores from `data/human_baseline/analysis`.
- `model_setting_summary.csv`: model CRPS/MAE summaries for three settings.
- `model_template_horizon_summary.csv`: primary-setting breakdown by model, target template, and horizon.
- `aggregate_comparison.csv`: descriptive human-vs-model normalized CRPS differences with independent bootstrap intervals.
- `coverage_and_metadata.json`: run source, model list, setting definitions, and coverage diagnostics.

## Primary Setting

`primary_same_targets_same_horizons` is the closest proxy to the human pilot:

- same forecast format: continuous p10/p25/p50/p75/p90 model forecasts scored with quantile CRPS;
- same target families: city count, discovered technologies, and treasury/gold;
- same resolution turns: H1/H3/H4/H6, corresponding to turns 90/150/180/240;
- different worlds and civilizations: model results come from the existing seed0-seed10 run, while humans saw `seed1327` and `seed1976`.

The primary model sample has 660 possible predictions per model: 11 worlds x 5 civilizations x 3 target families x 4 horizons. The human pilot has 24 crowd-level questions and 240 individual forecasts from 10 participants.

## Inference Caveat

The bootstrap intervals in `aggregate_comparison.csv` resample model questions and human questions or participants independently. They are useful for describing uncertainty in aggregate scores, but they should not be presented as a clean head-to-head significance test because the human and model forecasts are not on the same questions.
""",
        encoding="utf-8",
    )


def serializable_settings() -> dict:
    out = {}
    for name, setting in COMPARISON_SETTINGS.items():
        out[name] = {
            "description": setting["description"],
            "templates": sorted(setting["templates"]) if setting["templates"] is not None else None,
            "horizons": sorted(setting["horizons"]),
            "normalized": setting["normalized"],
            "comparison_grade": setting["comparison_grade"],
        }
    return out


def main() -> int:
    args = parse_args()
    rng = random.Random(args.seed)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    model_run = json.loads(args.model_run.read_text(encoding="utf-8"))
    models = list(model_run["model_results"].keys())
    human_ranges = load_human_ranges(args.human_questions)
    model_score_rows, coverage = score_model_questions(model_run, human_ranges)
    model_summary_rows, setting_values = summarize_model_settings(
        model_score_rows,
        models,
        args.bootstrap_samples,
        rng,
    )
    template_horizon_rows = summarize_template_horizon(model_score_rows, models)
    human_reference_rows, human_values = load_human_reference(args.human_analysis_dir)
    comparison_rows = compare_to_humans(
        model_summary_rows,
        setting_values,
        human_reference_rows,
        human_values,
        args.bootstrap_samples,
        rng,
    )

    write_csv(args.output_dir / "human_reference_summary.csv", human_reference_rows)
    write_csv(args.output_dir / "model_setting_summary.csv", model_summary_rows)
    write_csv(args.output_dir / "model_template_horizon_summary.csv", template_horizon_rows)
    write_csv(args.output_dir / "aggregate_comparison.csv", comparison_rows)

    metadata = {
        "model_run": str(args.model_run),
        "model_run_id": model_run.get("metadata", {}).get("run_id"),
        "model_run_start_time": model_run.get("metadata", {}).get("start_time"),
        "model_run_end_time": model_run.get("metadata", {}).get("end_time"),
        "model_question_type_distribution": model_run.get("metadata", {}).get("question_type_distribution"),
        "human_question_file": str(args.human_questions),
        "human_analysis_dir": str(args.human_analysis_dir),
        "bootstrap_samples": args.bootstrap_samples,
        "models": models,
        "n_models": len(models),
        "human_ranges": human_ranges,
        "settings": serializable_settings(),
        "coverage": coverage,
        "comparability": {
            "equivalent_conditions": False,
            "why_not_equivalent": [
                "Humans and models were not evaluated on the same worlds or civilizations.",
                "The human pilot used a Quorum UI with five probability bins; existing model runs used text prompts and p10/p25/p50/p75/p90 outputs.",
                "The primary comparison matches target families and horizons, but it remains an aggregate proxy.",
            ],
            "most_defensible_claim": (
                "Existing LLM aggregate normalized CRPS on matched target families and horizons can be compared "
                "descriptively to the human pilot; it should not be treated as a matched human baseline."
            ),
        },
    }
    (args.output_dir / "coverage_and_metadata.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    write_readme(args.output_dir / "README.md")

    print(json.dumps({
        "output_dir": str(args.output_dir),
        "n_models": len(models),
        "primary_setting": "primary_same_targets_same_horizons",
        "primary_possible_predictions_per_model": 660,
        "human_crowd_questions": 24,
        "human_individual_forecasts": 240,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
